---
- name: Ensure that BIND is not installed in order to avoid conflicts with dnsmasq
  apt:
    package: bind9
    state: absent

- name: Disable systemd-resolved and mask it
  systemd:
    name: systemd-resolved
    enabled: no
    masked: yes
    state: stopped

- name: Remove resolv file
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create temporary resolv file
  copy:
    dest: "/etc/resolv.conf"
    content: |
      nameserver 8.8.8.8

- name: Install dnsmasq
  apt:
    package: dnsmasq

- name: Generate the dnsmasq configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Create the dnsmasq systemd drop-in configuration directory
  file:
    path: "{{ dnsmasq_systemd_service_path }}"
    state: directory

- name: Generate the dnsmasq systemd drop-in service file
  template:
    src: dnsmasq.service.j2
    dest: "{{ dnsmasq_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the dnsmasq service
  systemd:
    daemon_reload: yes
    name: dnsmasq.service
    enabled: yes
    state: restarted

- name: Update resolv file to use local server
  copy:
    dest: "/etc/resolv.conf"
    content: |
      nameserver 127.0.0.1

